name: run amazon-price-tracker.py

on:
  push:
    branches:
      - develop
  schedule:
  #  - cron: '0 7 * * *' #Ogni giorno alle 9 di mattina (7 UTC)
    - cron: '0 */6 * * *' #At minute 0 past every 6th hour
  #  - cron: '*/5 * * * *' #ogni 5 minuti, debug
  workflow_dispatch:

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: checkout repo content
              uses: actions/checkout@v2 #checkout the repository content to github runner
            
            - name: setup python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.9' #install the python version needed
            
            - name: install python packages
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            
            - name: execute py script #run pizza_toni_scraper.py
              env:
                    SOME_SECRET: ${{secrets.SOME_SECRET}}
              run: python pizza_toni_scraper.py

            - name: commit files
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add -A
                git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

            - name: push changes
              uses: ad-m/github-push-action@v0.6.0
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: develop
